### ISSUE TITLE
Test Project with Microsoft SQL Server

### ISSUE THREAD

**Issue by PaigeM89** [louisfischer/Cake.EntityFramework#5]
With the TODO of "Test More Type Providers", should we test with Microsoft SQL Server? I could build a test project in the same structure as the PostgresQL. I'm not sure if we will find a lot of differences between the providers, but it could also be useful to provide another framework.

This would also be beneficial as I am unable to run the PostgresQL tests at all, as installing it on my system caused some very odd issues that were only resolved once it was uninstalled. I am left only with SQL Server, which is what I'm using in production anyways.

**Comment by Silvenga** [comment]
That would be great, I used Postgres primarily because EF sometimes has trouble loading third-party drivers (EF always loads the MSSQL driver). 

Appveyor has a SQL server that we can test against.

I used (https://github.com/louisfischer/Cake.EntityFramework/tree/master/docker/postgres) via Docker for Windows to test Postgress without installing it.

**Comment by PaigeM89** [comment]
I am not familiar with Docker and Appveyor. I could do the drudge work of setting up the SQL server project, but leave it to someone else to configure the Docker setup for it? Assuming it would need the same project setup. Otherwise it may take me a bit longer to get something set up for testing.

**Comment by louisfischer** [comment]
This is good issue. I have some experience with using EF with SQL Server and migrations. This is one issue I was going to add  but it looks like you beat me to it

**Comment by louisfischer** [comment]
Completed from Pull Request #22
